### ISSUE TITLE
How to specify port behind proxy?

### ISSUE THREAD

**Issue by DanTulovsky** [8gears/n8n-helm-chart#1]
Hi,

I have an envoy_proxy (amabasador) in front of n8n.  If I set:

host: myhost.com
port: 443  # this is the port of the envoy proxy

then n8n fails to start because it fails to bind to port 443 (since it's not root).

If I leave port as the default, then the external webhook URL is: myhost.com:5678, which doesn't work from the outside.

How can I run n8n on it's default port, but have it properly set the webhook URL to myhost.com:443?

Thank you!
Dan

**Comment by DanTulovsky** [comment]
Specifically, not setting the port sets the POST URL for a github webhook to:

https://myhost.com:5678/webhook/3e5f0bdb-c416-4d1a-b1ec-117aa02f471f/webhook

Which is not available form the outside.  Setting the port to 443, leads to the "unable to bind" error.  

So I think I just need a way to set the external URL separately from what the server binds to.

**Comment by DanTulovsky** [comment]
I found https://docs.n8n.io/reference/configuration.html#webhook-url ...

**Comment by DanTulovsky** [comment]
Hmm.. the chart doesn't seem to provide a way to set  "WEBHOOK_TUNNEL_URL"... and there is no way to set arbitrary env variables either.. ?

**Comment by Vad1mo** [comment]
Everything is supported. Because it is just forwarded as is to N8n.

**Comment by DanTulovsky** [comment]
Ok.. but how would I set the "WEBHOOK_TUNNEL_URL" environment variable in the helm chart? Under what variable?

**Comment by DanTulovsky** [comment]
FYI, sent a pull request to handle this, wdyt?

**Comment by Vad1mo** [comment]
Version 0.2.0 is out (5 Jan, 2021)
