### ISSUE TITLE
Create Helm-chart release 0.24.0 on OCI Registry

### ISSUE THREAD

**Issue by albertollamaso** [8gears/n8n-helm-chart#104]
Hi Guys,

Any plan to create the 0.24.0 release on the OCI registry?. Let me know if I can help on this.

cheers

**Comment by Vad1mo** [comment]
check https://github.com/8gears/n8n-helm-chart/releases/tag/0.24.0

**Comment by albertollamaso** [comment]
Hi @Vad1mo,

0.24.0 does not exists as a release in the OCI registry and that's what I mean.

oci://8gears.container-registry.com/library/n8n

![image](https://github.com/user-attachments/assets/92bf4714-fba5-46e6-888b-c82c3e34ea99)

When trying to download the chart

```
could not download oci://8gears.container-registry.com/library/n8n: 8gears.container-registry.com/library/n8n:0.24.0: not found
```
This PR fix it https://github.com/8gears/n8n-helm-chart/pull/105
