### ISSUE TITLE
Helm Chart Installs n8n Version 1.49.0 Instead of Latest Release

### ISSUE THREAD

**Issue by VuiDJi** [8gears/n8n-helm-chart#111]
Hello,

I encountered an issue while installing the latest version of the n8n Helm chart. After running the installation, I noticed that the system deploys version 1.49.0. Upon starting n8n, it displays the following message:
"You’re on 1.49.0, which was released 2 weeks ago and is 1 version behind the latest and greatest n8n."

It seems that the Helm chart is not pulling the most recent version of n8n. Could you please check if the chart is updated with the latest release?

Thank you for your help!

**Comment by Vad1mo** [comment]
You can always set the application versions yourself. 
 This chart does not strictly follow the upstream n8n release schedule. 
 
 however I am happy to accept PRs, if you want to automte that.
