### ISSUE TITLE
Passing certificates for postgres client

### ISSUE THREAD

**Issue by lolinool** [8gears/n8n-helm-chart#113]
I can't transfer certificates, it's not entirely clear what needs to be specified in the section
`    ssl:
      ca:             # SSL certificate authority - default: ''
      cert:           # SSL certificate - default: ''
      key:            # SSL key - default: ''
      rejectUnauthorized:    # If unauthorized SSL connections should be rejected - default: true`
should there be a path or the encoded certificates themselves?
`       ssl:
         ca: "/home/ca.crt"           # SSL certificate authority - default: ''
         cert: "/home/client.crt"          # SSL certificate - default: ''
         key: "/home/client.key" `
at the moment my certificates are passed via secret.yaml in namespace and mounted to n8n pod but I still get the error
`Last session crashed
User settings loaded from: /home/node/.n8n/config
Loading config overwrites [ '/n8n-config/config.json', '/n8n-secret/secret.json' ]
Last session crashed
Initializing n8n process
Error: There was an error initializing DB
Error: error:0480006C:PEM routines::no start line`

**Comment by Vad1mo** [comment]
did you solve the issue, I can't make any sense of your question, given the title and cryptic information. 
This looks to me like a config related error.  

I am closing it, if the error persist and you think this is a problem on how this charts works please reopen with more information.
