### ISSUE TITLE
n8n version update

### ISSUE THREAD

**Issue by samuelrade** [8gears/n8n-helm-chart#114]
Any plans to upgrade to the latest [n8n version](https://docs.n8n.io/release-notes/#n8n1544) and release to https://artifacthub.io/packages/helm/open-8gears/n8n/?

**Comment by Vad1mo** [comment]
don't know why [/0.24.5](https://github.com/8gears/n8n-helm-chart/releases/tag/0.24.5) is not on ArtifactHub, will check
