### ISSUE TITLE
is 8gears dead now?

### ISSUE THREAD

**Issue by mayphilc** [8gears/n8n-helm-chart#128]
is this chart dead now? it doesnt support current releases in n8n and it appears nobody is maintaining it

**Comment by Vad1mo** [comment]
it is not dead: 

1. You can and should set the version that you would like in the chart. IMO there is not need to create a new chart for each app update. 
2. becaue of https://github.com/8gears/n8n-helm-chart/issues/125, we are drafting a new chart relase.

**Comment by mayphilc** [comment]
Ok so 1.68.0 and higher works with this chart now? When I tried to update before it wouldn't work at all and I needed up moving to a different chart but that'd been a nightmare and I'd really like to see this chart get the updates it needs to work, especially given the code node updates

**Comment by Vad1mo** [comment]
> 1.68.0

https://github.com/8gears/n8n-helm-chart/issues/125#issuecomment-2482414489
