### ISSUE TITLE
BasicAuth with Hash is not working

### ISSUE THREAD

**Issue by tl-Bruno-Braga** [8gears/n8n-helm-chart#13]
Hello 

I am trying to setup basic auth with n8n. I am using the hashed option which looking at the source code seems to indicate that a bcrypt hash should be set as N8N_BASIC_AUTH_PASSWORD.

When i enable hash:
```
config:  
 security:
    basicAuth:
      active: true
      hash: true
```

the basic auth on my browser keeps saying that the password is wrong. I have generated the bcrypt password using the following code:

```
var salt = bcrypt.genSaltSync(10);
console.log(process.env.N8N_PASSWORD)
var hash = bcrypt.hashSync(process.env.N8N_PASSWORD, salt);
console.log(hash)
```

Any reason why this is not working? Seems to work when i set hash to false and use normal password authentication.

Thanks

**Comment by Vad1mo** [comment]
I only tried it with username/password but your config settings seems to look good to me. I guess it is the hash itself,  can you try to run n8n locally seting the hash and debug the application  or ask the n8n team

**Comment by tl-Bruno-Braga** [comment]
https://github.com/n8n-io/n8n/issues/1835

Tried locally and same issue. Asked above.

**Comment by Vad1mo** [comment]
the helm chart is writing the config file that n8n is using, I tried to avoid using ENV Vars as in that case I need to support each one individually. can you please take a  look in your configMap, this one should contain the entry, if there is no entry then this is a problem with this helm chart.

**Comment by tl-Bruno-Braga** [comment]
This is the configmap:
```
{
  "listen_address": "0.0.0.0",
  "port": 5678,
  "protocol": "http",
  "security": {
    "basicAuth": {
      "active": true,
      "hash": true
    }
  }
}
```

Looking at config inside container: 

```
/data # cat /n8n-config/config.json
{
  "listen_address": "0.0.0.0",
  "port": 5678,
  "protocol": "http",
  "security": {
    "basicAuth": {
      "active": true,
      "hash": true
    }
  }
}
```

However, i would like to ask you to try and see if you can reproduce the issue on your side.

**Comment by Vad1mo** [comment]
where is the `password ` entry in the config file?
can you quote your hash in the yaml file?

**Comment by tl-Bruno-Braga** [comment]
We are integrating with vault so we source on a file with exports.

**Comment by Vad1mo** [comment]
I strongly think it's something on your side, maybe vault. This Helm chart just creates the config file that n8n used. 

try to hardcode the password bypassing vault and see if that works
