### ISSUE TITLE
basic auth in values yaml does not work

### ISSUE THREAD

**Issue by arrowcircle** [8gears/n8n-helm-chart#19]
Hey! It looks like basic auth from the values.yaml does not work.
It works fine if added via extra envs, but not in the security part of values.yaml.
Is it a bug or not done yet?

**Comment by stubbi** [comment]
Hey @arrowcircle did you prefix the value with either `config` or `secret`, i.e. `config.security.basicAuth.user` rather than `security.basicAuth.user`?

**Comment by Joffcom** [comment]
From v1 of n8n basic auth will no longer work.
