### ISSUE TITLE
How do add external js libraries?

### ISSUE THREAD

**Issue by DanTulovsky** [8gears/n8n-helm-chart#2]
Hi,

How can I add external js libraries using this helm chart?

Thank you
Dan

**Comment by Vad1mo** [comment]
Don’t know can you do it with n8n

**Comment by DanTulovsky** [comment]
https://community.n8n.io/t/help-not-been-able-to-import-external-modules/686/10

Seems like it's messy...

**Comment by Vad1mo** [comment]
There are a few options:

Side Car Container before n8n start:
1. Git Checkout 
2. S3 Bucket
3. Container that contains only the data and copies them on start to runtime.

Traditional Vol:
4. Volume Mount, question is how to get data in there? 


Opt. 3 is the easiest and most versatile. git and s3 have the challenge to add credentials and so on.

**Comment by Vad1mo** [comment]
@DanTulovsky where you able ro resolve the issue?

**Comment by DanTulovsky** [comment]
Sorry, I have up on n8n (for other reasons), so I didn't try.

**Comment by rafalkrupinski** [comment]
I created a new image, it's literally 2 lines of code.
Just publish it and set it in the config

**Comment by samuelrade** [comment]
@Vad1mo Is there any option without building a custom image to install external js library? We would need the `exif-js` module installed.

**Comment by rafalkrupinski** [comment]
Well, it is two line of code (FROM and RUN) but then you have to maintain it to keep it up to date, so not so great.
We could do an upgrade script and a template repo (image builder with up-to-date n8n with custom deps) but it would require some tests and I'm not sure how to approach it in this case.

**Comment by samuelrade** [comment]
Thanks! Those were exactly my concerns. If at all possible, I don't want to have to maintain a custom image.
Something like image builder would probably be the most sustainable solution.
