### ISSUE TITLE
Clarity: Worker vs Callback scalability

### ISSUE THREAD

**Issue by acrois** [8gears/n8n-helm-chart#20]
According to:
https://docs.n8n.io/getting-started/installation/advanced/scaling-n8n.html#running-n8n-with-queues

This chart does not seem to support this configuration. Any plans to in the future?

**Comment by Vad1mo** [comment]
Yes maybe, I don't know. Its not top of my prio at the moment. But I sure will look and merge it if someone create a PR

**Comment by swarnat** [comment]
Is implemented since #24
