### ISSUE TITLE
Derek app integration issue

### ISSUE THREAD

**Issue by alexellis** [8gears/n8n-helm-chart#3]
Hi, we are receiving webhooks from your repos into Derek, a GitHub bot run by OpenFaaS Ltd. Did you install Derek onto your org, and then decide not to use it?

Derek has a number of features including crediting contributors in release notes https://github.com/alexellis/derek

Feel free to reach out to me alex@openfaas.com

Alex

**Comment by Vad1mo** [comment]
Thank you, for the question, I updated the setting.

**Comment by alexellis** [comment]
You're welcome to use it, but you need to go through the instructions - https://github.com/alexellis/derek/blob/master/GET.md

I assumed someone in your team intended to, then got distracted?
