### ISSUE TITLE
Allow use of existing secrets for Postgres authentication

### ISSUE THREAD

**Issue by abaus-vc** [8gears/n8n-helm-chart#32]
Currently. any secrets you want the n8n deployment to use have to be placed explicitly in the values.yaml file; it is not possible to use existing secrets to provide credentials, for example for the postgres db password. However, this may be useful in certain scenarios.

Allowing to set additional environment variables, similar to what extraEnv does, but with a valueFrom/secretKeyRef instead of a fixed value would be one way to allow this.

**Comment by Vad1mo** [comment]
Agree, would make sense. I welcome any PR and would be happy to do a review!

**Comment by Yan-Solo** [comment]
Will this also be pushed to the registry?

**Comment by guitmz** [comment]
any news on that? this is pretty important for production setups, honestly a blocker in some cases

**Comment by guitmz** [comment]
@Vad1mo was this pushed to the registry already?
