### ISSUE TITLE
n8n pod failing to configure - no encryption key

### ISSUE THREAD

**Issue by Korinin38** [8gears/n8n-helm-chart#37]
According to `values.yaml`,
```
n8n:
  encryption_key: # n8n creates a random encryption key automatically on the first launch and saves it in the ~/.n8n folder. That key is used to encrypt the credentials before they get saved to the database.
```
I'm using helm on microk8s. With default `values.yaml` file, 
`
$ microk8s helm -f values.yaml install n8n open-8gears/n8n --debug
`
 results in pod with `CreateContainerConfigError`, specifically 
```
  Type     Reason             Age              From               Message
  ----     ------             ----             ----               -------
  Warning  Failed             3s (x3 over 4s)  kubelet            Error: secret "n8n" not found
```

No .n8n folder is created.
I managed to bypass the issue by typing encryption key into `values.yaml` manually.

**Comment by Korinin38** [comment]
Looks like #34 solves the issue. 
@Vad1mo I would appreciate if you could look into the request and merge it if possible. I'm happy to provide any help needed.

**Comment by cocuba** [comment]
Why is this closed? The problem still persists; the variable is not being created
