### ISSUE TITLE
Needing to customize `readiness`/`liveness` Probes

### ISSUE THREAD

**Issue by mhkarimi1383** [8gears/n8n-helm-chart#38]
sometimes for debugging, etc. we need more customization

**Comment by Vad1mo** [comment]
anything particular in mind?
Feel free to make a proposal and open a PR

**Comment by mhkarimi1383** [comment]
I want to know what is the preferred way?
Full customization or changing some parts?

**Comment by Vad1mo** [comment]
I don't know what options you have in mind?

Can you elaborate what you mean?

**Comment by mhkarimi1383** [comment]
You can put the entire readiness and liveness prob objecs inside or just put some parts of that (like enabling it or not, or time related values)

**Comment by Vad1mo** [comment]
Thanks, in that case, I would like to only configure, enable/disable and the timing in the chart.

It should be enabled in the chart

**Comment by mhkarimi1383** [comment]
I will try to do that in a PR
