### ISSUE TITLE
"webhook.enabled" means "webhook disabled"

### ISSUE THREAD

**Issue by zmatthias** [8gears/n8n-helm-chart#39]
Hello,

in line 264 values.yaml: https://github.com/8gears/n8n-helm-chart/blob/master/values.yaml
.Values.scaling.webhook.enabed is set to false:

``` 
 webhook:
    enabled: false
    count: 1

```

However, in line 95-97 _helpers.tpl: https://github.com/8gears/n8n-helm-chart/blob/master/templates/_helpers.tpl
the environment variable N8N_DISABLE_PRODUCTION_MAIN_PROCESS is set to true, if .Values.scaling.webhook.enabled is set to true:

```
{{- if .Values.scaling.webhook.enabled }}
- name: "N8N_DISABLE_PRODUCTION_MAIN_PROCESS"
  value: "true"
{{ end }}

```
[Description of N8N_DISABLE_PRODUCTION_MAIN_PROCESS](https://docs.n8n.io/hosting/environment-variables/environment-variables/): 

```
Disable production webhooks from main process. This helps ensure no HTTP traffic load to main process when using webhook-specific processes.
```

so seemlingly **"enabling" webhooks actually disables** them for production use. Debugging this caused us hours of headache.

**Comment by Vad1mo** [comment]
hmm, I see, what would you suggest solving the situation, and save many people a lot of debug time?

**Comment by zmatthias** [comment]
For example: rename .Values.scaling.webhook.enabed to .Values.scaling.webhook.**disabled**

```
 webhook:
    disabled: false
    count: 1
```

**Comment by Vad1mo** [comment]
This has a few flaws. Every service has the notation service.enabled. This is used here and is practice in other charts. It is also advised to do the same in general programming

Any other ideas?

**Comment by zmatthias** [comment]
Alright, I see. Then I think a simple comment would be sufficient and shouldn't do any harm :)
