### ISSUE TITLE
autoscaling/v2beta1 is outdated

### ISSUE THREAD

**Issue by acmeguy** [8gears/n8n-helm-chart#45]
Can you please upgrade this to autoscaling/v2beta2 or autoscaling/v2 ?

**Comment by swarnat** [comment]
I can provide the update to support k8s 1.25 in next 2 days, because I started to migrate first cluster to this version and I needs to implement this anyway.

**Comment by swarnat** [comment]
I think yes. The support with 1.25 was added with #46
