### ISSUE TITLE
Prevent workflow execution on master service

### ISSUE THREAD

**Issue by biclighter81** [8gears/n8n-helm-chart#52]
Hello together,
is it somehow possible to prevent the n8n master service from executing workflow especially if they are triggered by the manual "Execute workflow" node? We have some workflows which have high resource demands and if one of them fails because of lack of resources the master service, which provides the ui, should not crash. I only found the environment variable N8N_DISABLE_PRODUCTION_MAIN_PROCESS which only prevents webhook execution on the main process but not workflow execution.

Thank you for your help.

**Comment by FalkWolsky** [comment]
A solution and answer to this would be much appreciated. Same scenario here.
In our case, a Kafka-Trigger-based Workflow leads constantly to a crash of the Master Node, cause it automatically starts there.

**Comment by Vad1mo** [comment]
This is a Helm Chart only, you better ask n8n specific questions in the n8n forum.

You can configure this chart to use Any N8N option, but I don't know all the options.
