### ISSUE TITLE
semverCompare when version is in place

### ISSUE THREAD

**Issue by Paxhape** [8gears/n8n-helm-chart#53]
We are trying to use chart with automated pulling of newest version and images. We are fetching Chart and use helm template to gather images from templated chart.
We are getting 
```bash
helm template n8n n8n-0.12.1.tgz

Error: template: n8n/templates/deployment.yaml:73:31: executing "n8n/templates/deployment.yaml" at <semverCompare ">=1.0" .Values.image.tag>: error calling semverCompare: Invalid Semantic Version

Use --debug flag to render out invalid YAML
```

Is there possibility evaluate version after it was fetched ?

**Comment by Paxhape** [comment]
Maybe resolution is 
```yaml
mountPath: {{ if semverCompare ">=1.0.0" (.Values.image.tag | default .Chart.AppVersion) }}/home/node/.n8n{{ else }}/root/.n8n{{ end }}
```

**Comment by rkosegi** [comment]
There seems to be 2 issues here:
- `1.0` is not valid semantic version in expression `">=1.0"`
- expression is evaluated from left to right, so without parenthesis, `.Values.image.tag` is passed to `semverCompare` function and **then** is filter `default` called

**Comment by kplanz** [comment]
`1.0` is actually a valid semantic version expression. 
The problem is only the missing parenthesis, thanks for the PR!

Temporary fix for me was to specify the image tag manually.
