### ISSUE TITLE
The 'mountPath' of the PVC is not correctly pointing to the '/home/node/.n8n' path.

### ISSUE THREAD

**Issue by alvherrey** [8gears/n8n-helm-chart#55]
Hello, sorry if I am misunderstanding something, but when I deploy with Helm and enable persistence with the default SQLite database, the persistent volume is mounted at /root/.n8n, while all data is generated under /home/node/.n8n.

This implies that when I delete the pod, all data is lost. A workaround is to modify the deployment and map it to /home/node/.n8n, like this:
        **volumeMounts:
        - mountPath: /home/node/.n8n
          name: data**

But modifying the deployment in this way results in a loss of Helm deployment capability.

Environment:
kubernetes on k3s
n8nio/n8n Tag: 1.6.1
Chart Version: n8n-0.11.0 
Helm Version:"v3.12.3"

The values.yaml that I use:
https://pastebin.com/zYNE1CnF

**Comment by Vad1mo** [comment]
maybe @bartlaarhoven, can help here, as he created the PR.

**Comment by bartlaarhoven** [comment]
Correct, I ran into the same and created PR #49, which is merged into Chart version 0.12.0. So if you update your chart, it should work.

**Comment by alvherrey** [comment]
I confirm it works correctly after helm upgrade. 

Thanks!!
