### ISSUE TITLE
Feature Request - make a repo

### ISSUE THREAD

**Issue by egandro** [8gears/n8n-helm-chart#57]
Hello,

can you please create a simple repo?

- https://dev.to/frosnerd/using-a-private-github-repository-as-a-helm-chart-repository-5fa8
- https://www.harness.io/blog/helm-chart-repo

That is super nice + simple, as it requires only a few github action triggers.

Ping me if you need help.

Greetings.

**Comment by Vad1mo** [comment]
why would you want that?
