### ISSUE TITLE
EACCES: permission denied, open '/home/node/.n8n/config'

### ISSUE THREAD

**Issue by kaihsu1** [8gears/n8n-helm-chart#66]
EACCES: permission denied, open '/home/node/.n8n/config' #66

**Comment by Vad1mo** [comment]
https://upthemes.com/blog/2014/02/writing-useful-github-issues/

**Comment by omri-shilton** [comment]
im also experiencing this type of issue when setting 
```
persistence:
  enabled: true
  type: dynamic

```
