### ISSUE TITLE
503 Service Unavailable on repository fetch

### ISSUE THREAD

**Issue by PoulpiFr** [8gears/n8n-helm-chart#68]
Hello,

When running:
`helm install my-n8n oci://8gears.container-registry.com/library/n8n --version 0.20.1`, I have:

```
Error: INSTALLATION FAILED: unexpected status from HEAD request to https://8gears.container-registry.com/v2/library/n8n/manifests/0.20.1: 503 Service Unavailable
```

Previously during the day (2h ago), we had:

```

Error: INSTALLATION FAILED: failed to do request: Head "https://8gears.container-registry.com/v2/library/n8n/manifests/0.20.1": EOF
```

Is something wrong with the repository? Is there any official mirror available?

**Comment by PoulpiFr** [comment]
Thanks for fixing the issue.

It blocked our CI/CD for some hours so we'll have a look to how mirror / vendor this chart in the future to avoid getting such interruptions.

FYI, the move to OCI only is not helping as some artefact managers such as Sonatype Nexus are not yet compatible with OCI for Helm charts (while they work while using HTTP), see: https://github.com/sonatype/nexus-public/issues/201

**Comment by Vad1mo** [comment]
The general availability is good of the service. With this only exception, because of our cloud provider.

1 Jan 2023 — 1 Jan 2024	**99.9783%**	1 hour and 54 minutes	5	46 minutes	22 minutes

**Comment by PatrickHuetter** [comment]
I also think it might be too early for OCI only. We also have many problems switching from the old helm chart repository to the new one using argoCD.

```
Unable to save changes: application spec app-n8n is invalid: InvalidSpecError: Unable to generate manifests in : rpc error: code = Unknown desc = `helm pull oci://8gears.container-registry.com/library/n8n/n8n --version 0.20.1 --destination /tmp/4b72a37e-766c-4195-9117-d6c110b3c415` failed exit status 1: Error: 8gears.container-registry.com/library/n8n/n8n:0.20.1: not found
```
