### ISSUE TITLE
Helm 3.7+ version incompatibility

### ISSUE THREAD

**Issue by arrowcircle** [8gears/n8n-helm-chart#72]
Hey!
Looks like a latest (0.20.1) version of the chart is not compatible with recent helm versions due to the changes in helm 3.7 about OCI image format [Release notes](https://github.com/helm/helm/releases/tag/v3.7.0).

Could you please use new version of helm to build actual image of th chart, so it's possible to install n8n with recent helm version?

**Comment by Vad1mo** [comment]
can you elaborate a bit more what the problem is, to my knowledge `v3.14.0` was used to build that chart.

**Comment by Vad1mo** [comment]
can you give it a try with chart  **0.21.0**

**Comment by arrowcircle** [comment]
@Vad1mo It works. thanks for the help!
