### ISSUE TITLE
404 - failed to fetch

### ISSUE THREAD

**Issue by finkinfridom** [8gears/n8n-helm-chart#74]
I just upgraded my helm release to latest and the CI pipeline is failing because of 
`│ Error: looks like "[https://8gears.container-registry.com/chartrepo/library/"](https://8gears.container-registry.com/chartrepo/library/%22) is not a valid chart repository or cannot be reached: failed to fetch https://8gears.container-registry.com/chartrepo/library/index.yaml : 404 Not Found`

Did something recently changed?

**Comment by Vad1mo** [comment]
Yes, check the readme. We switched to OCI Charts.
