### ISSUE TITLE
Annotations resource-policy is not longer managed by Helm v3

### ISSUE THREAD

**Issue by Igor992** [8gears/n8n-helm-chart#8]
Hello,

Firstly, thanks for this great repository content and also for helmfile support!
During testing this content I saw that there is still following annotation which Helm v3 no longer supports.

![image](https://user-images.githubusercontent.com/54440160/112179773-43793080-8bfb-11eb-93a8-45212c89b86a.png)

*The annotation "helm.sh/resource-policy": keep instructs Helm to skip deleting this resource when a helm operation (such as helm uninstall, helm upgrade or helm rollback) would result in its deletion.*
**However, this resource becomes orphaned. Helm will no longer manage it in any way.**
*This can lead to problems if using helm install --replace on a release that has already been uninstalled, but has kept resources.*

Here is documentation as well regarding this topic [Helm](https://helm.sh/docs/howto/charts_tips_and_tricks/#tell-helm-not-to-uninstall-a-resource).

As I'm using helmfile for deployment, and currently pvc template can't exclude this annotation.

![image](https://user-images.githubusercontent.com/54440160/112182284-70c6de00-8bfd-11eb-9fb2-b8910437e932.png)

Sincerely,
Igor

**Comment by Vad1mo** [comment]
@Igor992 could you create a PR with the change, I'll will approve that ASAP

**Comment by Igor992** [comment]
@Vad1mo Sure, just to make some free time and I'll push PR.

**Comment by Vad1mo** [comment]
this is not how it usually works.
you need to fork and open a PR:

https://www.dataschool.io/how-to-contribute-on-github/

**Comment by Igor992** [comment]
Thanks for this documentation! I mostly work in organizational environments so I forgot this approach.

Don't forget to push a new chart with these patch fixes, so others can just reference it :)

![image](https://user-images.githubusercontent.com/54440160/112303876-1a10e100-8c9d-11eb-9441-9beaff536865.png)

Sincerely,
Igor

**Comment by Vad1mo** [comment]
0.6.0 is out
