### ISSUE TITLE
Chart at 0.23.0 raising "create: failed to create: Request entity too large: limit is 3145728"

### ISSUE THREAD

**Issue by finkinfridom** [8gears/n8n-helm-chart#83]
We tried to upgrade the chart to version `0.23.0` but the install (performed through `terraform apply`) failed because of `create: failed to create: Request entity too large: limit is 3145728` error.

We tried to downgrade the chart to version `0.22.0` and everything works as expected.

**Comment by Vad1mo** [comment]
I don't know what that means, can you provide more context?

**Comment by Vad1mo** [comment]
I see that chart is 2 MiB instead of 100 KiB, can you give it a try now, it should be fixed!

**Comment by finkinfridom** [comment]
I confirm it's fixed. Thanks for the fast resolution
